// Generated by: hibernate/SpringHibernateDaoImpl.vsl in andromda-spring-cartridge.
// license-header java merge-point
/**
 * This is only generated once! It will never be overwritten.
 * You can (and have to!) safely modify it by hand.
 */
package com.systemsjr.jrbase.counter;

import com.systemsjr.jrbase.counter.vo.CounterVO;

/**
 * @see Counter
 */
public class CounterDaoImpl
    extends CounterDaoBase
{
    /**
     * {@inheritDoc}
     */
    public void toCounterVO(
        Counter source,
        CounterVO target)
    {
        // TODO verify behavior of toCounterVO
        super.toCounterVO(source, target);
    }

    /**
     * {@inheritDoc}
     */
    public CounterVO toCounterVO(final Counter entity)
    {
        // TODO verify behavior of toCounterVO
        return super.toCounterVO(entity);
    }

    /**
     * Retrieves the entity object that is associated with the specified value object
     * from the object store. If no such entity object exists in the object store,
     * a new, blank entity is created
     */
    private Counter loadCounterFromCounterVO(CounterVO counterVO)
    {
        // TODO implement loadCounterFromCounterVO
        throw new UnsupportedOperationException("com.systemsjr.jrbase.counter.loadCounterFromCounterVO(CounterVO) not yet implemented.");

        /* A typical implementation looks like this:
        Counter counter = this.get(counterVO.getId());
        if (counter == null)
        {
            counter = Counter.Factory.newInstance();
        }
        return counter;
        */
    }

    /**
     * {@inheritDoc}
     */
    public Counter counterVOToEntity(CounterVO counterVO)
    {
        // TODO verify behavior of counterVOToEntity
        Counter entity = this.loadCounterFromCounterVO(counterVO);
        this.counterVOToEntity(counterVO, entity, true);
        return entity;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void counterVOToEntity(
        CounterVO source,
        Counter target,
        boolean copyIfNull)
    {
        // TODO verify behavior of counterVOToEntity
        super.counterVOToEntity(source, target, copyIfNull);
    }
}