// license-header java merge-point
// Generated by andromda-jsf cartridge (controllers\crud\ControllerImpl.java.vsl) on 02/01/2013 19:07:46+0200
package com.systemsjr.jrbase.individual.crud;

import java.io.Serializable;

/**
 * @see com.systemsjr.jrbase.individual.crud.IndividualController
 */
public class IndividualControllerImpl
    extends IndividualController
    implements Serializable
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 4486620879102097263L;
}