// license-header java merge-point
// Generated by andromda-jsf cartridge (controllers\crud\ControllerImpl.java.vsl) on 02/06/2013 16:36:29+0200
package com.systemsjr.jrbase.individual.crud;

import java.io.Serializable;

/**
 * @see com.systemsjr.jrbase.individual.crud.NextOfKinController
 */
public class NextOfKinControllerImpl
    extends NextOfKinController
    implements Serializable
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = -5002771800889481179L;
}