SET DEFINE OFF;
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('PY', 'PARAGUAY', 'AREA_TYPE', 'ACTIVE', 2, 'PY', 'PARAGUAY');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('QA', 'QATAR', 'AREA_TYPE', 'ACTIVE', 2, 'QA', 'QATAR');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('RE', 'REUNION (FRENCH)', 'AREA_TYPE', 'ACTIVE', 2, 'RE', 'REUNION (FRENCH)');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('RO', 'ROMANIA', 'AREA_TYPE', 'ACTIVE', 2, 'RO', 'ROMANIA');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('RU', 'RUSSIAN FEDERATION', 'AREA_TYPE', 'ACTIVE', 2, 'RU', 'RUSSIAN FEDERATION');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('RW', 'RWANDA', 'AREA_TYPE', 'ACTIVE', 2, 'RW', 'RWANDA');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('SA', 'SAUDI ARABIA', 'AREA_TYPE', 'ACTIVE', 2, 'SA', 'SAUDI ARABIA');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('SB', 'SOLOMON ISLANDS', 'AREA_TYPE', 'ACTIVE', 2, 'SB', 'SOLOMON ISLANDS');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('SC', 'SEYCHELLES', 'AREA_TYPE', 'ACTIVE', 2, 'SC', 'SEYCHELLES');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('SD', 'SUDAN', 'AREA_TYPE', 'ACTIVE', 2, 'SD', 'SUDAN');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('SE', 'SWEDEN', 'AREA_TYPE', 'ACTIVE', 2, 'SE', 'SWEDEN');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('SG', 'SINGAPORE', 'AREA_TYPE', 'ACTIVE', 2, 'SG', 'SINGAPORE');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('SH', 'SAINT HELENA', 'AREA_TYPE', 'ACTIVE', 2, 'SH', 'SAINT HELENA');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('SI', 'SLOVENIA', 'AREA_TYPE', 'ACTIVE', 2, 'SI', 'SLOVENIA');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('SJ', 'SVALBARD AND JAN MAYEN ISLANDS', 'AREA_TYPE', 'ACTIVE', 2, 'SJ', 'SVALBARD AND JAN MAYEN ISLANDS');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('SK', 'SLOVAK REPUBLIC', 'AREA_TYPE', 'ACTIVE', 2, 'SK', 'SLOVAK REPUBLIC');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('SL', 'SIERRA LEONE', 'AREA_TYPE', 'ACTIVE', 2, 'SL', 'SIERRA LEONE');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('SM', 'SAN MARINO', 'AREA_TYPE', 'ACTIVE', 2, 'SM', 'SAN MARINO',);
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('SO', 'SOMALIA', 'AREA_TYPE', 'ACTIVE', 2, 'SO', 'SOMALIA');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('SR', 'SURINAME', 'AREA_TYPE', 'ACTIVE', 2, 'SR', 'SURINAME');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('SU', 'FORMER USSR', 'AREA_TYPE', 'ACTIVE', 2, 'SU', 'FORMER USSR');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('SV', 'EL SALVADOR', 'AREA_TYPE', 'ACTIVE', 2, 'SV', 'EL SALVADOR');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('SY', 'SYRIA', 'AREA_TYPE', 'ACTIVE', 2, 'SY', 'SYRIA');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('SZ', 'SWAZILAND', 'AREA_TYPE', 'ACTIVE', 2, 'SZ', 'SWAZILAND');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('TD', 'CHAD', 'AREA_TYPE', 'ACTIVE', 2, 'TD', 'CHAD');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('TF', 'FRENCH SOUTHERN TERRITORIES', 'AREA_TYPE', 'ACTIVE', 2, 'TF', 'FRENCH SOUTHERN TERRITORIES');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('TG', 'TOGO', 'AREA_TYPE', 'ACTIVE', 2,'TG', 'TOGO' );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('TH', 'THAILAND', 'AREA_TYPE', 'ACTIVE', 2, 'TH', 'THAILAND');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('TK', 'TOKELAU', 'AREA_TYPE', 'ACTIVE', 2, 'TK', 'TOKELAU');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('TM', 'TURKMENISTAN', 'AREA_TYPE', 'ACTIVE', 2, 'TM', 'TURKMENISTAN');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('TN', 'TUNISIA', 'AREA_TYPE', 'ACTIVE', 2, 'TN', 'TUNISIA');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('TP', 'EAST TIMOR', 'AREA_TYPE', 'ACTIVE', 2, 'TP', 'EAST TIMOR');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('TR', 'TURKEY', 'AREA_TYPE', 'ACTIVE', 2, 'TR', 'TURKEY');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('TV', 'TUVALU', 'AREA_TYPE', 'ACTIVE', 2, 'TV', 'TUVALU');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('TW', 'TAIWAN', 'AREA_TYPE', 'ACTIVE', 2, 'TW', 'TAIWAN',);
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('TZ', 'TANZANIA', 'AREA_TYPE', 'ACTIVE', 2, 'TZ', 'TANZANIA');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('UA', 'UKRAINE', 'AREA_TYPE', 'ACTIVE', 2, 'UA', 'UKRAINE');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('UK', 'UNITED KINGDOM', 'AREA_TYPE', 'ACTIVE', 2, 'UK', 'UNITED KINGDOM');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('UM', 'USA MINOR OUTLYING ISLANDS', 'AREA_TYPE', 'ACTIVE', 2,'UM', 'USA MINOR OUTLYING ISLANDS' );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('UY', 'URUGUAY', 'AREA_TYPE', 'ACTIVE', 2, 'UY', 'URUGUAY');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('UZ', 'UZBEKISTAN', 'AREA_TYPE', 'ACTIVE', 2,'UZ', 'UZBEKISTAN' );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('VA', 'HOLY SEE (VATICAN CITY STATE)', 'AREA_TYPE', 'ACTIVE', 2,'VA', 'HOLY SEE (VATICAN CITY STATE)' );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('VE', 'VENEZUELA', 'AREA_TYPE', 'ACTIVE', 2, 'VE', 'VENEZUELA');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('VG', 'VIRGIN ISLANDS (BRITISH)', 'AREA_TYPE', 'ACTIVE', 2, 'VG', 'VIRGIN ISLANDS (BRITISH)');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('VI', 'VIRGIN ISLANDS (USA)', 'AREA_TYPE', 'ACTIVE', 2,'VI', 'VIRGIN ISLANDS (USA)' );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('VN', 'VIETNAM', 'AREA_TYPE', 'ACTIVE', 2,'VN', 'VIETNAM' );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('WF', 'WALLIS AND FUTUNA ISLANDS', 'AREA_TYPE', 'ACTIVE', 2, 'WF', 'WALLIS AND FUTUNA ISLANDS');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('WS', 'SAMOA', 'AREA_TYPE', 'ACTIVE', 2,'WS', 'SAMOA' );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('YE', 'YEMEN', 'AREA_TYPE', 'ACTIVE', 2, 'YE', 'YEMEN');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('YU', 'YUGOSLAVIA', 'AREA_TYPE', 'ACTIVE', 2, 'YU', 'YUGOSLAVIA');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('ZA', 'SOUTH AFRICA', 'AREA_TYPE', 'ACTIVE', 2,'ZA', 'SOUTH AFRICA', );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('ZR', 'ZAIRE', 'AREA_TYPE', 'ACTIVE', 2, 'ZR', 'ZAIRE');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('ZW', 'ZIMBABWE', 'AREA_TYPE', 'ACTIVE', 2, 'ZW', 'ZIMBABWE');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('CI', 'IVORY COAST (COTE D''IVOIRE)', 'AREA_TYPE', 'ACTIVE', 2, 'CI', 'IVORY COAST (COTE D''IVOIRE)',);
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('CS', 'FORMER CZECHOSLOVAKIA', 'AREA_TYPE', 'ACTIVE', 2, 'CS', 'FORMER CZECHOSLOVAKIA');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('CY', 'CYPRUS', 'AREA_TYPE', 'ACTIVE', 2, 'CY', 'CYPRUS');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('DJ', 'DJIBOUTI', 'AREA_TYPE', 'ACTIVE', 2,'DJ', 'DJIBOUTI' );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('EG', 'EGYPT', 'AREA_TYPE', 'ACTIVE', 2, 'EG', 'EGYPT');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('ES', 'SPAIN', 'AREA_TYPE', 'ACTIVE', 2, 'ES', 'SPAIN');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('FJ', 'FIJI', 'AREA_TYPE', 'ACTIVE', 2, 'FJ', 'FIJI');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('GA', 'GABON', 'AREA_TYPE', 'ACTIVE', 2, 'GA', 'GABON');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('GE', 'GEORGIA', 'AREA_TYPE', 'ACTIVE', 2, 'GE', 'GEORGIA');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('GI', 'GIBRALTAR', 'AREA_TYPE', 'ACTIVE', 2, );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('GT', 'GUATEMALA', 'AREA_TYPE', 'ACTIVE', 2, 'GT', 'GUATEMALA');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('GY', 'GUYANA', 'AREA_TYPE', 'ACTIVE', 2, 'GY', 'GUYANA');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('HN', 'HONDURAS', 'AREA_TYPE', 'ACTIVE', 2, 'HN', 'HONDURAS');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('IL', 'ISRAEL', 'AREA_TYPE', 'ACTIVE', 2, 'IL', 'ISRAEL');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('IQ', 'IRAQ', 'AREA_TYPE', 'ACTIVE', 2, 'IQ', 'IRAQ');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('IT', 'ITALY', 'AREA_TYPE', 'ACTIVE', 2, 'IT', 'ITALY');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('KH', 'CAMBODIA, KINGDOM OF', 'AREA_TYPE', 'ACTIVE', 2, 'KH', 'CAMBODIA, KINGDOM OF');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('KP', 'NORTH KOREA', 'AREA_TYPE', 'ACTIVE', 2, 'KP', 'NORTH KOREA');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('LC', 'SAINT LUCIA', 'AREA_TYPE', 'ACTIVE', 2, 'LC', 'SAINT LUCIA');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('LR', 'LIBERIA', 'AREA_TYPE', 'ACTIVE', 2, 'LR', 'LIBERIA');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('BM', 'BERMUDA', 'AREA_TYPE', 'ACTIVE', 2, );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('BS', 'BAHAMAS', 'AREA_TYPE', 'ACTIVE', 2, );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('BW', 'BOTSWANA', 'AREA_TYPE', 'ACTIVE', 2, 'BW', 'BOTSWANA');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('CC', 'COCOS (KEELING) ISLANDS', 'AREA_TYPE', 'ACTIVE', 2, 'CC', 'COCOS (KEELING) ISLANDS');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('CK', 'COOK ISLANDS', 'AREA_TYPE', 'ACTIVE', 2, 'CK', 'COOK ISLANDS');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('CR', 'COSTA RICA', 'AREA_TYPE', 'ACTIVE', 2, 'CR', 'COSTA RICA');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('CX', 'CHRISTMAS ISLAND', 'AREA_TYPE', 'ACTIVE', 2, 'CX', 'CHRISTMAS ISLAND');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('DZ', 'ALGERIA', 'AREA_TYPE', 'ACTIVE', 2, 'DZ', 'ALGERIA');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('EH', 'WESTERN SAHARA', 'AREA_TYPE', 'ACTIVE', 2, 'EH', 'WESTERN SAHARA');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('FK', 'FALKLAND ISLANDS', 'AREA_TYPE', 'ACTIVE', 2, 'FK', 'FALKLAND ISLANDS');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('GB', 'GREAT BRITAIN', 'AREA_TYPE', 'ACTIVE', 2, 'GB', 'GREAT BRITAIN');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('GL', 'GREENLAND', 'AREA_TYPE', 'ACTIVE', 2, 'GL', 'GREENLAND');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('GR', 'GREECE', 'AREA_TYPE', 'ACTIVE', 2, 'GR', 'GREECE');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('HK', 'HONG KONG', 'AREA_TYPE', 'ACTIVE', 2, 'HK', 'HONG KONG');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('ID', 'INDONESIA', 'AREA_TYPE', 'ACTIVE', 2, 'ID', 'INDONESIA');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('IO', 'BRITISH INDIAN OCEAN TERRITORY', 'AREA_TYPE', 'ACTIVE', 2, 'IO', 'BRITISH INDIAN OCEAN TERRITORY');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('KE', 'KENYA', 'AREA_TYPE', 'ACTIVE', 2, 'KE', 'KENYA');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('KN', 'SAINT KITTS & NEVIS ANGUILLA', 'AREA_TYPE', 'ACTIVE', 2,'KN', 'SAINT KITTS & NEVIS ANGUILLA' );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('SN', 'SENEGAL', 'AREA_TYPE', 'ACTIVE', 2, 'SN', 'SENEGAL');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('ST', 'SAINT TOME (SAO TOME) AND PRINCIPE', 'AREA_TYPE', 'ACTIVE', 2, 'ST', 'SAINT TOME (SAO TOME) AND PRINCIPE');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('TC', 'TURKS AND CAICOS ISLANDS', 'AREA_TYPE', 'ACTIVE', 2, 'TC', 'TURKS AND CAICOS ISLANDS');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('TJ', 'TADJIKISTAN', 'AREA_TYPE', 'ACTIVE', 2, );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('TO', 'TONGA', 'AREA_TYPE', 'ACTIVE', 2, );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('TT', 'TRINIDAD AND TOBAGO', 'AREA_TYPE', 'ACTIVE', 2, 'TT', 'TRINIDAD AND TOBAGO');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('UG', 'UGANDA', 'AREA_TYPE', 'ACTIVE', 2, 'UG', 'UGANDA');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('US', 'UNITED STATES OF AMERICA', 'AREA_TYPE', 'ACTIVE', 2, 'US', 'UNITED STATES OF AMERICA');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('VC', 'SAINT VINCENT & GRENADINES', 'AREA_TYPE', 'ACTIVE', 2, 'VC', 'SAINT VINCENT & GRENADINES');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('VU', 'VANUATU', 'AREA_TYPE', 'ACTIVE', 2, 'VU', 'VANUATU');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('YT', 'MAYOTTE', 'AREA_TYPE', 'ACTIVE', 2, 'YT', 'MAYOTTE');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('ZM', 'ZAMBIA', 'AREA_TYPE', 'ACTIVE', 2, 'ZM', 'ZAMBIA');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('CN', 'CHINA', 'AREA_TYPE', 'ACTIVE', 2, 'CN', 'CHINA');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('DO', 'DOMINICAN REPUBLIC', 'AREA_TYPE', 'ACTIVE', 2, 'DO', 'DOMINICAN REPUBLIC');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('FO', 'FAROE ISLANDS', 'AREA_TYPE', 'ACTIVE', 2, 'FO', 'FAROE ISLANDS');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('GP', 'GUADELOUPE (FRENCH)', 'AREA_TYPE', 'ACTIVE', 2, 'GP', 'GUADELOUPE (FRENCH)');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('HU', 'HUNGARY', 'AREA_TYPE', 'ACTIVE', 2, 'HU', 'HUNGARY');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('JP', 'JAPAN', 'AREA_TYPE', 'ACTIVE', 2, 'JP', 'JAPAN');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('KY', 'CAYMAN ISLANDS', 'AREA_TYPE', 'ACTIVE', 2, 'KY', 'CAYMAN ISLANDS');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('LU', 'LUXEMBOURG', 'AREA_TYPE', 'ACTIVE', 2, 'LU', 'LUXEMBOURG');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('MA', 'MOROCCO', 'AREA_TYPE', 'ACTIVE', 2, 'MA', 'MOROCCO');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('MG', 'MADAGASCAR', 'AREA_TYPE', 'ACTIVE', 2, 'MG', 'MADAGASCAR');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('MM', 'MYANMAR', 'AREA_TYPE', 'ACTIVE', 2, 'MM', 'MYANMAR');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('MP', 'NORTHERN MARIANA ISLANDS', 'AREA_TYPE', 'ACTIVE', 2, 'MP', 'NORTHERN MARIANA ISLANDS');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('MT', 'MALTA', 'AREA_TYPE', 'ACTIVE', 2, 'MT', 'MALTA');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('OM', 'OMAN', 'AREA_TYPE', 'ACTIVE', 2, 'OM', 'OMAN');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('MU', 'MAURITIUS', 'AREA_TYPE', 'ACTIVE', 2, 'MU', 'MAURITIUS');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('MV', 'MALDIVES', 'AREA_TYPE', 'ACTIVE', 2, 'MV', 'MALDIVES');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('MW', 'MALAWI', 'AREA_TYPE', 'ACTIVE', 2, 'MW', 'MALAWI');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('MX', 'MEXICO', 'AREA_TYPE', 'ACTIVE', 2, 'MX', 'MEXICO');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('MY', 'MALAYSIA', 'AREA_TYPE', 'ACTIVE', 2, 'MY', 'MALAYSIA');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('MZ', 'MOZAMBIQUE', 'AREA_TYPE', 'ACTIVE', 2, 'MZ', 'MOZAMBIQUE');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('NA', 'NAMIBIA', 'AREA_TYPE', 'ACTIVE', 2, 'NA', 'NAMIBIA');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('NC', 'NEW CALEDONIA (FRENCH)', 'AREA_TYPE', 'ACTIVE', 2, 'NC', 'NEW CALEDONIA (FRENCH)');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('NE', 'NIGER', 'AREA_TYPE', 'ACTIVE', 2, 'NE', 'NIGER');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('NF', 'NORFOLK ISLAND', 'AREA_TYPE', 'ACTIVE', 2, 'NF', 'NORFOLK ISLAND');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('NG', 'NIGERIA', 'AREA_TYPE', 'ACTIVE', 2, 'NG', 'NIGERIA');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('NI', 'NICARAGUA', 'AREA_TYPE', 'ACTIVE', 2, 'NI', 'NICARAGUA');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('NL', 'NETHERLANDS', 'AREA_TYPE', 'ACTIVE', 2, 'NL', 'NETHERLANDS');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('NO', 'NORWAY', 'AREA_TYPE', 'ACTIVE', 2, 'NO', 'NORWAY');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('NP', 'NEPAL', 'AREA_TYPE', 'ACTIVE', 2, 'NP', 'NEPAL');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('NR', 'NAURU', 'AREA_TYPE', 'ACTIVE', 2, 'NR', 'NAURU');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('NT', 'NEUTRAL ZONE', 'AREA_TYPE', 'ACTIVE', 2, 'NT', 'NEUTRAL ZONE');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('AD', 'ANDORRA, PRINCIPALITY OF', 'AREA_TYPE', 'ACTIVE', 2, 'AD', 'ANDORRA');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('AE', 'UNITED ARAB EMIRATES', 'AREA_TYPE', 'ACTIVE', 2, 'AE', 'UNITED ARAB EMIRATES');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('AF', 'AFGHANISTAN, ISLAMIC STATE OF', 'AREA_TYPE', 'ACTIVE', 2,'AF', 'AFGHANISTAN, ISLAMIC STATE OF' );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('AG', 'ANTIGUA AND BARBUDA', 'AREA_TYPE', 'ACTIVE', 2, 'AG', 'ANTIGUA AND BARBUDA');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('AI', 'ANGUILLA', 'AREA_TYPE', 'ACTIVE', 2, 'AI', 'ANGUILLA');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('AL', 'ALBANIA', 'AREA_TYPE', 'ACTIVE', 2, 'AL', 'ALBANIA');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('AM', 'ARMENIA', 'AREA_TYPE', 'ACTIVE', 2, );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('AN', 'NETHERLANDS ANTILLES', 'AREA_TYPE', 'ACTIVE', 2, 'AN', 'NETHERLANDS ANTILLES');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('AO', 'ANGOLA', 'AREA_TYPE', 'ACTIVE', 2, 'AO', 'ANGOLA',);
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('AQ', 'ANTARCTICA', 'AREA_TYPE', 'ACTIVE', 2, 'AQ', 'ANTARCTICA');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('AR', 'ARGENTINA', 'AREA_TYPE', 'ACTIVE', 2, 'AR', 'ARGENTINA');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('AS', 'AMERICAN SAMOA', 'AREA_TYPE', 'ACTIVE', 2, 'AS', 'AMERICAN SAMOA');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('AT', 'AUSTRIA', 'AREA_TYPE', 'ACTIVE', 2, 'AT', 'AUSTRIA');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('AU', 'AUSTRALIA', 'AREA_TYPE', 'ACTIVE', 2, 'AU', 'AUSTRALIA');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('AW', 'ARUBA', 'AREA_TYPE', 'ACTIVE', 2, 'AU', 'AUSTRALIA');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('AZ', 'AZERBAIDJAN', 'AREA_TYPE', 'ACTIVE', 2, );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('BA', 'BOSNIA-HERZEGOVINA', 'AREA_TYPE', 'ACTIVE', 2, );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('BB', 'BARBADOS', 'AREA_TYPE', 'ACTIVE', 2, );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('BD', 'BANGLADESH', 'AREA_TYPE', 'ACTIVE', 2, );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('BE', 'BELGIUM', 'AREA_TYPE', 'ACTIVE', 2, );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('BF', 'BURKINA FASO', 'AREA_TYPE', 'ACTIVE', 2, );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('BG', 'BULGARIA', 'AREA_TYPE', 'ACTIVE', 2, );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('BH', 'BAHRAIN', 'AREA_TYPE', 'ACTIVE', 2, );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('BI', 'BURUNDI', 'AREA_TYPE', 'ACTIVE', 2, );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('BJ', 'BENIN', 'AREA_TYPE', 'ACTIVE', 2, );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('BN', 'BRUNEI DARUSSALAM', 'AREA_TYPE', 'ACTIVE', 2, );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('BO', 'BOLIVIA', 'AREA_TYPE', 'ACTIVE', 2, );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('BR', 'BRAZIL', 'AREA_TYPE', 'ACTIVE', 2, );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('BT', 'BHUTAN', 'AREA_TYPE', 'ACTIVE', 2, );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('BV', 'BOUVET ISLAND', 'AREA_TYPE', 'ACTIVE', 2, );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('BY', 'BELARUS', 'AREA_TYPE', 'ACTIVE', 2, );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('BZ', 'BELIZE', 'AREA_TYPE', 'ACTIVE', 2, );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('CA', 'CANADA', 'AREA_TYPE', 'ACTIVE', 2, );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('CF', 'CENTRAL AFRICAN REPUBLIC', 'AREA_TYPE', 'ACTIVE', 2, );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('CD', 'CONGO, THE DEMOCRATIC REPUBLIC OF THE', 'AREA_TYPE', 'ACTIVE', 2, );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('CG', 'CONGO', 'AREA_TYPE', 'ACTIVE', 2, );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('CH', 'SWITZERLAND', 'AREA_TYPE', 'ACTIVE', 2, );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('CL', 'CHILE', 'AREA_TYPE', 'ACTIVE', 2, );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('CM', 'CAMEROON', 'AREA_TYPE', 'ACTIVE', 2, );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('CO', 'COLOMBIA', 'AREA_TYPE', 'ACTIVE', 2, );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('CU', 'CUBA', 'AREA_TYPE', 'ACTIVE', 2, );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('CV', 'CAPE VERDE', 'AREA_TYPE', 'ACTIVE', 2, );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('CZ', 'CZECH REPUBLIC', 'AREA_TYPE', 'ACTIVE', 2, );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('DE', 'GERMANY', 'AREA_TYPE', 'ACTIVE', 2, );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('DK', 'DENMARK', 'AREA_TYPE', 'ACTIVE', 2, );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('DM', 'DOMINICA', 'AREA_TYPE', 'ACTIVE', 2, );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('EC', 'ECUADOR', 'AREA_TYPE', 'ACTIVE', 2, );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('EE', 'ESTONIA', 'AREA_TYPE', 'ACTIVE', 2, );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('ER', 'ERITREA', 'AREA_TYPE', 'ACTIVE', 2, );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('ET', 'ETHIOPIA', 'AREA_TYPE', 'ACTIVE', 2, );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('FI', 'FINLAND', 'AREA_TYPE', 'ACTIVE', 2, );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('FM', 'MICRONESIA', 'AREA_TYPE', 'ACTIVE', 2, );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('FR', 'FRANCE', 'AREA_TYPE', 'ACTIVE', 2, );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('FX', 'FRANCE (EUROPEAN TERRITORY)', 'AREA_TYPE', 'ACTIVE', 2, );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('GD', 'GRENADA', 'AREA_TYPE', 'ACTIVE', 2, );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('GF', 'FRENCH GUYANA', 'AREA_TYPE', 'ACTIVE', 2, );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('GH', 'GHANA', 'AREA_TYPE', 'ACTIVE', 2, );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('GM', 'GAMBIA', 'AREA_TYPE', 'ACTIVE', 2, );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('GN', 'GUINEA', 'AREA_TYPE', 'ACTIVE', 2, );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('GQ', 'EQUATORIAL GUINEA', 'AREA_TYPE', 'ACTIVE', 2, );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('GS', 'S. GEORGIA & S. SANDWICH ISLS.', 'AREA_TYPE', 'ACTIVE', 2, );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('GU', 'GUAM (USA)', 'AREA_TYPE', 'ACTIVE', 2, );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('GW', 'GUINEA BISSAU', 'AREA_TYPE', 'ACTIVE', 2, );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('HM', 'HEARD AND MCDONALD ISLANDS', 'AREA_TYPE', 'ACTIVE', 2, );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('HR', 'CROATIA', 'AREA_TYPE', 'ACTIVE', 2, );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('HT', 'HAITI', 'AREA_TYPE', 'ACTIVE', 2, );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('IE', 'IRELAND', 'AREA_TYPE', 'ACTIVE', 2, );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('IN', 'INDIA', 'AREA_TYPE', 'ACTIVE', 2, );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('IR', 'IRAN', 'AREA_TYPE', 'ACTIVE', 2, );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('IS', 'ICELAND', 'AREA_TYPE', 'ACTIVE', 2, );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('JM', 'JAMAICA', 'AREA_TYPE', 'ACTIVE', 2, );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('JO', 'JORDAN', 'AREA_TYPE', 'ACTIVE', 2, );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('KG', 'KYRGYZ REPUBLIC (KYRGYZSTAN)', 'AREA_TYPE', 'ACTIVE', 2, );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('KI', 'KIRIBATI', 'AREA_TYPE', 'ACTIVE', 2, );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('KM', 'COMOROS', 'AREA_TYPE', 'ACTIVE', 2, );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('KR', 'SOUTH KOREA', 'AREA_TYPE', 'ACTIVE', 2, );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('KW', 'KUWAIT', 'AREA_TYPE', 'ACTIVE', 2, );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('KZ', 'KAZAKHSTAN', 'AREA_TYPE', 'ACTIVE', 2, );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('LA', 'LAOS', 'AREA_TYPE', 'ACTIVE', 2, );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('LB', 'LEBANON', 'AREA_TYPE', 'ACTIVE', 2, );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('LI', 'LIECHTENSTEIN', 'AREA_TYPE', 'ACTIVE', 2, );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('LK', 'SRI LANKA', 'AREA_TYPE', 'ACTIVE', 2, );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('LS', 'LESOTHO', 'AREA_TYPE', 'ACTIVE', 2, );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('LT', 'LITHUANIA', 'AREA_TYPE', 'ACTIVE', 2, );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('LV', 'LATVIA', 'AREA_TYPE', 'ACTIVE', 2, );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('LY', 'LIBYA', 'AREA_TYPE', 'ACTIVE', 2, );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('MC', 'MONACO', 'AREA_TYPE', 'ACTIVE', 2, );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('MD', 'MOLDAVIA', 'AREA_TYPE', 'ACTIVE', 2, );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('MH', 'MARSHALL ISLANDS', 'AREA_TYPE', 'ACTIVE', 2, );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('MK', 'MACEDONIA', 'AREA_TYPE', 'ACTIVE', 2, );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('ML', 'MALI', 'AREA_TYPE', 'ACTIVE', 2, );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('MN', 'MONGOLIA', 'AREA_TYPE', 'ACTIVE', 2, );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('MO', 'MACAU', 'AREA_TYPE', 'ACTIVE', 2, );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('MQ', 'MARTINIQUE (FRENCH)', 'AREA_TYPE', 'ACTIVE', 2, );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('MR', 'MAURITANIA', 'AREA_TYPE', 'ACTIVE', 2, );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('MS', 'MONTSERRAT', 'AREA_TYPE', 'ACTIVE', 2, );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('NU', 'NIUE', 'AREA_TYPE', 'ACTIVE', 2, );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('NZ', 'NEW ZEALAND', 'AREA_TYPE', 'ACTIVE', 2, );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('PA', 'PANAMA', 'AREA_TYPE', 'ACTIVE', 2, );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('PE', 'PERU', 'AREA_TYPE', 'ACTIVE', 2, );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('PF', 'POLYNESIA (FRENCH)', 'AREA_TYPE', 'ACTIVE', 2, );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('PG', 'PAPUA NEW GUINEA', 'AREA_TYPE', 'ACTIVE', 2, 'PG', 'PAPUA NEW GUINEA');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('PH', 'PHILIPPINES', 'AREA_TYPE', 'ACTIVE', 2, 'PH', 'PHILIPPINES');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('PK', 'PAKISTAN', 'AREA_TYPE', 'ACTIVE', 2, 'PK', 'PAKISTAN');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('PL', 'POLAND', 'AREA_TYPE', 'ACTIVE', 2, 'PL', 'POLAND');
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('PM', 'SAINT PIERRE AND MIQUELON', 'AREA_TYPE', 'ACTIVE', 2, );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('PN', 'PITCAIRN ISLAND', 'AREA_TYPE', 'ACTIVE', 2, );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('PR', 'PUERTO RICO', 'AREA_TYPE', 'ACTIVE', 2, );
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('PT', 'PORTUGAL', 'AREA_TYPE', 'ACTIVE', 2, 'PT', 'PORTUGAL',);
Insert into LOCATIONS
   (UNIQUE_CODE, DESCRIPTION, TYPE, STATUS, LOCATION_TYPE_FK, LEVEL_CODE, LOCATION_NAME)
 Values
   ('PW', 'PALAU', 'AREA_TYPE', 'ACTIVE', 2, 'PW', 'PALAU');
COMMIT;
