// Generated by: hibernate/SpringHibernateDaoImpl.vsl in andromda-spring-cartridge.
// license-header java merge-point
/**
 * This is only generated once! It will never be overwritten.
 * You can (and have to!) safely modify it by hand.
 */
package com.systemsjr.jrbase.loginsession;

import com.systemsjr.jrbase.loginsession.vo.LoginSearchCriteria;
import com.systemsjr.jrbase.loginsession.vo.LoginSessionVO;
import java.util.List;

/**
 * @see LoginSession
 */
public class LoginSessionDaoImpl
    extends LoginSessionDaoBase
{
    /**
     * {@inheritDoc}
     */
    protected List handleFindByCriteria(LoginSearchCriteria searchCriteria)
    {
        // TODO implement public List handleFindByCriteria(LoginSearchCriteria searchCriteria)
        return null;
}

    /**
     * {@inheritDoc}
     */
    public void toLoginSessionVO(
        LoginSession source,
        LoginSessionVO target)
    {
        // TODO verify behavior of toLoginSessionVO
        super.toLoginSessionVO(source, target);
        // WARNING! No conversion for target.user (can't convert source.getUser():com.systemsjr.jrbase.user.User to com.systemsjr.jrbase.user.vo.UserVO
        // WARNING! No conversion for target.area (can't convert source.getArea():com.systemsjr.jrbase.location.Location to com.systemsjr.jrbase.location.vo.LocationVO
    }

    /**
     * {@inheritDoc}
     */
    public LoginSessionVO toLoginSessionVO(final LoginSession entity)
    {
        // TODO verify behavior of toLoginSessionVO
        return super.toLoginSessionVO(entity);
    }

    /**
     * Retrieves the entity object that is associated with the specified value object
     * from the object store. If no such entity object exists in the object store,
     * a new, blank entity is created
     */
    private LoginSession loadLoginSessionFromLoginSessionVO(LoginSessionVO loginSessionVO)
    {
        // TODO implement loadLoginSessionFromLoginSessionVO
        throw new UnsupportedOperationException("com.systemsjr.jrbase.loginsession.loadLoginSessionFromLoginSessionVO(LoginSessionVO) not yet implemented.");

        /* A typical implementation looks like this:
        LoginSession loginSession = this.get(loginSessionVO.getId());
        if (loginSession == null)
        {
            loginSession = LoginSession.Factory.newInstance();
        }
        return loginSession;
        */
    }

    /**
     * {@inheritDoc}
     */
    public LoginSession loginSessionVOToEntity(LoginSessionVO loginSessionVO)
    {
        // TODO verify behavior of loginSessionVOToEntity
        LoginSession entity = this.loadLoginSessionFromLoginSessionVO(loginSessionVO);
        this.loginSessionVOToEntity(loginSessionVO, entity, true);
        return entity;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void loginSessionVOToEntity(
        LoginSessionVO source,
        LoginSession target,
        boolean copyIfNull)
    {
        // TODO verify behavior of loginSessionVOToEntity
        super.loginSessionVOToEntity(source, target, copyIfNull);
    }
}