<!-- Generated by andromda-jsf cartridge (views\jsp\index.jsp.vsl) DO NOT EDIT! -->
<%response.sendRedirect(request.getContextPath() + "/crud-index.jsf"+(request.getQueryString() != null ? "?"+request.getQueryString() : ""));%>
