// license-header java merge-point
// Generated by andromda-jsf cartridge (controllers\ControllerImpl.java.vsl)
package com.systemsjr.jrbase.role.web.search;

import java.util.Collection;

import com.systemsjr.jrbase.role.vo.RoleSearchCriteria;
import com.systemsjr.jrbase.role.vo.RoleVO;

/**
 * @see com.systemsjr.jrbase.role.web.search.RoleSearchController
 */
public class RoleSearchControllerImpl
    extends RoleSearchController
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = -6147083992951200605L;

    /**
     * @see com.systemsjr.jrbase.role.web.search.RoleSearchController#doInitialiseSearchScreen(com.systemsjr.jrbase.role.vo.RoleSearchCriteria searchCriteria)
     */
    @Override
    public void doInitialiseSearchScreen(DoInitialiseSearchScreenForm form)
    {
        form.setSearchCriteria(new RoleSearchCriteria());
    }

    /**
     * @see com.systemsjr.jrbase.role.web.search.RoleSearchController#doRolesSearch()
     */
    @Override
    public void doRolesSearch()
    {
    	Collection<RoleVO> roles = getRoleService().searchRoles(getSearchRolesSearchForm().getSearchCriteria());
    	getSearchRolesSearchForm().setRoles(roles);
    }

    /**
     * @see com.systemsjr.jrbase.role.web.search.RoleSearchController#doRoleEdit(java.lang.Long id, com.systemsjr.jrbase.role.vo.RoleVO roleVO)
     */
    @Override
    public void doRoleEdit(DoRoleEditForm form)
    {
        form.setRoleVO(getRoleService().findById(form.getId()));
    }

    /**
     * @see com.systemsjr.jrbase.role.web.search.RoleSearchController#doRoleDetails(java.lang.Long id, com.systemsjr.jrbase.role.vo.RoleVO roleVO)
     */
    @Override
    public void doRoleDetails(DoRoleDetailsForm form)
    {
        form.setRoleVO(getRoleService().findById(form.getId()));
    }
}