// Generated by: hibernate/SpringHibernateDaoImpl.vsl in andromda-spring-cartridge.
// license-header java merge-point
/**
 * This is only generated once! It will never be overwritten.
 * You can (and have to!) safely modify it by hand.
 */
package com.systemsjr.jrbase.individual;

import com.systemsjr.jrbase.individual.vo.IndividualSearchCriteria;
import com.systemsjr.jrbase.individual.vo.IndividualVO;
import java.util.List;

/**
 * @see Individual
 */
public class IndividualDaoImpl
    extends IndividualDaoBase
{
    /**
     * {@inheritDoc}
     */
    protected List handleFindByCriteria(IndividualSearchCriteria searchCriteria)
    {
        // TODO implement public List handleFindByCriteria(IndividualSearchCriteria searchCriteria)
        return null;
}

    /**
     * {@inheritDoc}
     */
    public void toIndividualVO(
        Individual source,
        IndividualVO target)
    {
        // TODO verify behavior of toIndividualVO
        super.toIndividualVO(source, target);
        // WARNING! No conversion for target.nextOfKins (can't convert source.getNextOfKins():com.systemsjr.jrbase.individual.NextOfKin to com.systemsjr.jrbase.individual.vo.NextOfKinVO[]
        // WARNING! No conversion for target.countryOfBirth (can't convert source.getCountryOfBirth():com.systemsjr.jrbase.location.Location to com.systemsjr.jrbase.location.vo.LocationVO
        // WARNING! No conversion for target.countryOfCitizenship (can't convert source.getCountryOfCitizenship():com.systemsjr.jrbase.location.Location to com.systemsjr.jrbase.location.vo.LocationVO
    }

    /**
     * {@inheritDoc}
     */
    public IndividualVO toIndividualVO(final Individual entity)
    {
        // TODO verify behavior of toIndividualVO
        return super.toIndividualVO(entity);
    }

    /**
     * Retrieves the entity object that is associated with the specified value object
     * from the object store. If no such entity object exists in the object store,
     * a new, blank entity is created
     */
    private Individual loadIndividualFromIndividualVO(IndividualVO individualVO)
    {
        // TODO implement loadIndividualFromIndividualVO
        throw new UnsupportedOperationException("com.systemsjr.jrbase.individual.loadIndividualFromIndividualVO(IndividualVO) not yet implemented.");

        /* A typical implementation looks like this:
        Individual individual = this.get(individualVO.getId());
        if (individual == null)
        {
            individual = Individual.Factory.newInstance();
        }
        return individual;
        */
    }

    /**
     * {@inheritDoc}
     */
    public Individual individualVOToEntity(IndividualVO individualVO)
    {
        // TODO verify behavior of individualVOToEntity
        Individual entity = this.loadIndividualFromIndividualVO(individualVO);
        this.individualVOToEntity(individualVO, entity, true);
        return entity;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void individualVOToEntity(
        IndividualVO source,
        Individual target,
        boolean copyIfNull)
    {
        // TODO verify behavior of individualVOToEntity
        super.individualVOToEntity(source, target, copyIfNull);
    }
}