// Generated by: hibernate/SpringHibernateDaoImpl.vsl in andromda-spring-cartridge.
// license-header java merge-point
/**
 * This is only generated once! It will never be overwritten.
 * You can (and have to!) safely modify it by hand.
 */
package com.systemsjr.jrbase.individual;

import com.systemsjr.jrbase.individual.vo.NextOfKinVO;

/**
 * @see NextOfKin
 */
public class NextOfKinDaoImpl
    extends NextOfKinDaoBase
{
    /**
     * {@inheritDoc}
     */
    public void toNextOfKinVO(
        NextOfKin source,
        NextOfKinVO target)
    {
        // TODO verify behavior of toNextOfKinVO
        super.toNextOfKinVO(source, target);
        // WARNING! No conversion for target.individual (can't convert source.getIndividual():com.systemsjr.jrbase.individual.Individual to com.systemsjr.jrbase.individual.vo.IndividualVO
        // WARNING! No conversion for target.kin (can't convert source.getKin():com.systemsjr.jrbase.individual.Individual to com.systemsjr.jrbase.individual.vo.IndividualVO
    }

    /**
     * {@inheritDoc}
     */
    public NextOfKinVO toNextOfKinVO(final NextOfKin entity)
    {
        // TODO verify behavior of toNextOfKinVO
        return super.toNextOfKinVO(entity);
    }

    /**
     * Retrieves the entity object that is associated with the specified value object
     * from the object store. If no such entity object exists in the object store,
     * a new, blank entity is created
     */
    private NextOfKin loadNextOfKinFromNextOfKinVO(NextOfKinVO nextOfKinVO)
    {
        // TODO implement loadNextOfKinFromNextOfKinVO
        throw new UnsupportedOperationException("com.systemsjr.jrbase.individual.loadNextOfKinFromNextOfKinVO(NextOfKinVO) not yet implemented.");

        /* A typical implementation looks like this:
        NextOfKin nextOfKin = this.get(nextOfKinVO.getId());
        if (nextOfKin == null)
        {
            nextOfKin = NextOfKin.Factory.newInstance();
        }
        return nextOfKin;
        */
    }

    /**
     * {@inheritDoc}
     */
    public NextOfKin nextOfKinVOToEntity(NextOfKinVO nextOfKinVO)
    {
        // TODO verify behavior of nextOfKinVOToEntity
        NextOfKin entity = this.loadNextOfKinFromNextOfKinVO(nextOfKinVO);
        this.nextOfKinVOToEntity(nextOfKinVO, entity, true);
        return entity;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void nextOfKinVOToEntity(
        NextOfKinVO source,
        NextOfKin target,
        boolean copyIfNull)
    {
        // TODO verify behavior of nextOfKinVOToEntity
        super.nextOfKinVOToEntity(source, target, copyIfNull);
    }
}