// Generated by: hibernate/SpringHibernateDaoImpl.vsl in andromda-spring-cartridge.
// license-header java merge-point
/**
 * This is only generated once! It will never be overwritten.
 * You can (and have to!) safely modify it by hand.
 */
package com.systemsjr.jrbase.user;

import com.systemsjr.jrbase.user.vo.UserDetailsVO;
import com.systemsjr.jrbase.user.vo.UserSearchCriteria;
import com.systemsjr.jrbase.user.vo.UserVO;
import java.util.List;

/**
 * @see User
 */
public class UserDaoImpl
    extends UserDaoBase
{
    /**
     * {@inheritDoc}
     */
    protected List handleFindByCriteria(UserSearchCriteria searchCriteria)
    {
        // TODO implement public List handleFindByCriteria(UserSearchCriteria searchCriteria)
        return null;
}

    /**
     * {@inheritDoc}
     */
    protected User handleUserLogin(String username, String password)
    {
        // TODO implement public User handleUserLogin(String username, String password)
        return null;
}

    /**
     * {@inheritDoc}
     */
    protected User handleGetUserDetails(String username)
    {
        // TODO implement public User handleGetUserDetails(String username)
        return null;
}

    /**
     * {@inheritDoc}
     */
    public void toUserVO(
        User source,
        UserVO target)
    {
        // TODO verify behavior of toUserVO
        super.toUserVO(source, target);
        // WARNING! No conversion for target.individual (can't convert source.getIndividual():com.systemsjr.jrbase.individual.Individual to com.systemsjr.jrbase.individual.vo.IndividualVO
    }

    /**
     * {@inheritDoc}
     */
    public UserVO toUserVO(final User entity)
    {
        // TODO verify behavior of toUserVO
        return super.toUserVO(entity);
    }

    /**
     * Retrieves the entity object that is associated with the specified value object
     * from the object store. If no such entity object exists in the object store,
     * a new, blank entity is created
     */
    private User loadUserFromUserVO(UserVO userVO)
    {
        // TODO implement loadUserFromUserVO
        throw new UnsupportedOperationException("com.systemsjr.jrbase.user.loadUserFromUserVO(UserVO) not yet implemented.");

        /* A typical implementation looks like this:
        User user = this.get(userVO.getId());
        if (user == null)
        {
            user = User.Factory.newInstance();
        }
        return user;
        */
    }

    /**
     * {@inheritDoc}
     */
    public User userVOToEntity(UserVO userVO)
    {
        // TODO verify behavior of userVOToEntity
        User entity = this.loadUserFromUserVO(userVO);
        this.userVOToEntity(userVO, entity, true);
        return entity;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void userVOToEntity(
        UserVO source,
        User target,
        boolean copyIfNull)
    {
        // TODO verify behavior of userVOToEntity
        super.userVOToEntity(source, target, copyIfNull);
    }
    /**
     * {@inheritDoc}
     */
    public void toUserDetailsVO(
        User source,
        UserDetailsVO target)
    {
        // TODO verify behavior of toUserDetailsVO
        super.toUserDetailsVO(source, target);
        // WARNING! No conversion for target.individual (can't convert source.getIndividual():com.systemsjr.jrbase.individual.Individual to com.systemsjr.jrbase.individual.vo.IndividualVO
        // WARNING! No conversion for target.userClearanceLevels (can't convert source.getUserClearanceLevels():com.systemsjr.jrbase.clearancelevel.ClearanceLevel to com.systemsjr.jrbase.clearancelevel.vo.ClearanceLevelVO[]
        // WARNING! No conversion for target.userRoles (can't convert source.getUserRoles():com.systemsjr.jrbase.role.Role to com.systemsjr.jrbase.role.vo.RoleVO[]
        // WARNING! No conversion for target.userLocations (can't convert source.getUserLocations():com.systemsjr.jrbase.user.UserLocation to com.systemsjr.jrbase.user.vo.UserLocationVO[]
    }

    /**
     * {@inheritDoc}
     */
    public UserDetailsVO toUserDetailsVO(final User entity)
    {
        // TODO verify behavior of toUserDetailsVO
        return super.toUserDetailsVO(entity);
    }

    /**
     * Retrieves the entity object that is associated with the specified value object
     * from the object store. If no such entity object exists in the object store,
     * a new, blank entity is created
     */
    private User loadUserFromUserDetailsVO(UserDetailsVO userDetailsVO)
    {
        // TODO implement loadUserFromUserDetailsVO
        throw new UnsupportedOperationException("com.systemsjr.jrbase.user.loadUserFromUserDetailsVO(UserDetailsVO) not yet implemented.");

        /* A typical implementation looks like this:
        User user = this.get(userDetailsVO.getId());
        if (user == null)
        {
            user = User.Factory.newInstance();
        }
        return user;
        */
    }

    /**
     * {@inheritDoc}
     */
    public User userDetailsVOToEntity(UserDetailsVO userDetailsVO)
    {
        // TODO verify behavior of userDetailsVOToEntity
        User entity = this.loadUserFromUserDetailsVO(userDetailsVO);
        this.userDetailsVOToEntity(userDetailsVO, entity, true);
        return entity;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void userDetailsVOToEntity(
        UserDetailsVO source,
        User target,
        boolean copyIfNull)
    {
        // TODO verify behavior of userDetailsVOToEntity
        super.userDetailsVOToEntity(source, target, copyIfNull);
    }
}