// license-header java merge-point
// Generated by andromda-jsf cartridge (controllers\ControllerImpl.java.vsl)
package com.systemsjr.jrbase.role.web.edit;

import com.systemsjr.jrbase.role.vo.RoleVO;
import java.util.Date;

/**
 * @see com.systemsjr.jrbase.role.web.edit.RoleEditController
 */
public class RoleEditControllerImpl
    extends RoleEditController
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 4376484496164077717L;

    /**
     * @see com.systemsjr.jrbase.role.web.edit.RoleEditController#doInitialiseEditScreen(RoleVO roleVO)
     */
    @Override
    public void doInitialiseEditScreen(DoInitialiseEditScreenForm form)
    {
        // populating value with dummy instance
        RoleVO roleVO = new RoleVO();
        roleVO.setId(new Long((long)3355));
        roleVO.setRole(null);
        roleVO.setRoleDescription(null);
        roleVO.setRoleCode(null);
        roleVO.setRoleClearanceLevels(null);
        roleVO.setUsers(null);
        roleVO.setCreatedBy(null);
        roleVO.setCreatedAt(new Date());
        roleVO.setModifiedBy(null);
        roleVO.setModifiedAt(new Date());
        form.setRoleVO(roleVO);
    }


    /**
     * @see com.systemsjr.jrbase.role.web.edit.RoleEditController#doRemoveRole(RoleVO roleVO)
     */
    @Override
    public void doRemoveRole(DoRemoveRoleForm form)
    {
        // populating value with dummy instance
        RoleVO roleVO = new RoleVO();
        roleVO.setId(new Long((long)3355));
        roleVO.setRole(null);
        roleVO.setRoleDescription(null);
        roleVO.setRoleCode(null);
        roleVO.setRoleClearanceLevels(null);
        roleVO.setUsers(null);
        roleVO.setCreatedBy(null);
        roleVO.setCreatedAt(new Date());
        roleVO.setModifiedBy(null);
        roleVO.setModifiedAt(new Date());
        form.setRoleVO(roleVO);
    }

    /**
     * @see com.systemsjr.jrbase.role.web.edit.RoleEditController#doSaveRole(RoleVO roleVO)
     */
    @Override
    public void doSaveRole(DoSaveRoleForm form)
    {
        // populating value with dummy instance
        RoleVO roleVO = new RoleVO();
        roleVO.setId(new Long((long)3355));
        roleVO.setRole(null);
        roleVO.setRoleDescription(null);
        roleVO.setRoleCode(null);
        roleVO.setRoleClearanceLevels(null);
        roleVO.setUsers(null);
        roleVO.setCreatedBy(null);
        roleVO.setCreatedAt(new Date());
        roleVO.setModifiedBy(null);
        roleVO.setModifiedAt(new Date());
        form.setRoleVO(roleVO);
    }


	@Override
	public void doNewRole(DoNewRoleForm form) throws Throwable {
		// TODO Auto-generated method stub
		form.setRoleVO(new RoleVO());
	}

}